### ISSUE TITLE
Missing Font

### ISSUE THREAD

**Issue by NeoCortex3** [jlesage/docker-baseimage-gui#132]
Firtst of all: What a great baseimage! An awesome tool to create my own docker images, thank you!

I wanted a dockercontainer with the filemanager "krusader" so i git cloned the repo.
In "Dockerfile" I added:
```
ARG BASEIMAGE=jlesage/baseimage-gui:alpine-3.19-v4
RUN add-pkg krusader
COPY startapp.sh /startapp.sh
RUN set-cont-env APP_NAME "krusader"
```

In "startapp.sh" I have:
```
#!/bin/sh
exec /usr/bin/krusader
```

My Docker-Stack looks like this:
```
services:
    neotest:
        image: neo-test1:latest
        container_name: neo-test
        volumes:
            - config:/config
        ports:
            - 9075:5800
        environment:
            - USER_ID=1000 # user neo
            - GROUP_ID=100 # gruppe "users"
            - UMASK=0000
            - TZ=Europe/Berlin
            #- LANG=de_DE.UTF-8
        restart: unless-stopped

volumes:
  config:
```

This all works fine. The Image builds, den Container starts, the application starts, but I'm missing the font.
![Screenshot 2024-06-26 203607](https://github.com/jlesage/docker-baseimage-gui/assets/10122405/61e1ab44-bf00-49cd-ba36-f68f89c46e33)

I have absolutly no clue what I can do about this. Any help would be great.
