### ISSUE TITLE
Trying my hand to get Darktable running

### ISSUE THREAD

**Issue by ovizii** [jlesage/docker-baseimage-gui#68]
I am using: 

`FROM jlesage/baseimage-gui:debian-11`

trying to run darktable from this repo: https://software.opensuse.org/download.html?project=graphics:darktable&package=darktable 

Building the image works fine but when running it I get this error and I can't seem to figure out what is wrong. It has most probably not related to this base image but I thought I'd ask while I keep searching the net.

```
(process:839): GLib-GObject-CRITICAL **: 07:10:36.869: g_object_set: assertion 'G_IS_OBJECT (object)' failed                                         
path lookup '/run/s6/services/app/                                                                                                                   
' fails with: 'No such file or directory'                                                                                                            
[services.d] stopping services                                                                                                                       
[services.d] stopping app...                                                                                                                         
[services.d] stopping logmonitor...                                                                                                                  
[services.d] stopping statusmonitor...                                                                                                               
[services.d] stopping x11vnc...                                                                                                                      
caught signal: 15                         
```

**Comment by ovizii** [comment]
Just in case, here is the Dockerfile:

```
# Pull base image.                                                                                                                                                                                                                                                                                                   
FROM jlesage/baseimage-gui:debian-11                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                     
# Install desired stuff                                                                                                                                                                                                                                                                                              
RUN apt-get update && \                                                                                                                                                                                                                                                                                              
    apt-get install -y apt-utils gpg curl git procps && \                                                                                                                                                                                                                                                            
    echo 'deb http://download.opensuse.org/repositories/graphics:/darktable/Debian_11/ /' | tee /etc/apt/sources.list.d/graphics:darktable.list && \                                                                                                                                                                 
    curl -fsSL https://download.opensuse.org/repositories/graphics:darktable/Debian_11/Release.key | gpg --dearmor | tee /etc/apt/trusted.gpg.d/graphics_darktable.gpg > /dev/null && \                                                                                                                              
    apt-get update && \                                                                                                                                                                                                                                                                                              
    apt-get dist-upgrade -y && \                                                                                                                                                                                                                                                                                     
    apt-get install -y darktable                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                     
# Copy the start script.                                                                                                                                                                                                                                                                                             
COPY startapp.sh /startapp.sh                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                     
# Set the name of the application.                                                                                                                                                                                                                                                                                   
ENV APP_NAME="DarkTable"  
```

**Comment by ovizii** [comment]
And my startapp.sh

```
#!/bin/sh                                                                                                                                                                                                                                                                                                            
exec darktable --configdir /config/.config/darktable/ --disable-opencl 
```

I added '--disable-opencl' as the error above seemed related to opencl, but it didn't help

**Comment by ovizii** [comment]
docker-compose.yml

```
version: '2.2'                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                     
services:                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                     
# https://github.com/jlesage/docker-baseimage-gui                                                                                                                                                                                                                                                                    
# https://www.darktable.org/                                                                                                                                                                                                                                                                                         
    darktable:                                                                                                                                                                                                                                                                                                       
        build: .                                                                                                                                                                                                                                                                                                     
        image: ovidarktable                                                                                                                                                                                                                                                                                          
        container_name: darktable                                                                                                                                                                                                                                                                                    
        hostname: darktable                                                                                                                                                                                                                                                                                          
        restart: "no"                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                     
        ports:                                                                                                                                                                                                                                                                                                       
          - 5805:5800                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                     
        environment:                                                                                                                                                                                                                                                                                                 
          - USER_ID=1000                                                                                                                                                                                                                                                                                             
          - GROUP_ID=1000                                                                                                                                                                                                                                                                                            
          - DISPLAY_WIDTH=2560                                                                                                                                                                                                                                                                                       
          - DISPLAY_HEIGHT=1440                                                                                                                                                                                                                                                                                      
          - KEEP_APP_RUNNING=1                                                                                                                                                                                                                                                                                       
          - HOME=/config                                                                                                                                                                                                                                                                                             

                                                                                                                                                                                                                                                                                                                     
        volumes:                                                                                                                                                                                                                                                                                                     
          - /etc/timezone:/etc/timezone:ro                                                                                                                                                                                                                                                                           
          - ./config:/config                                                                                                                                                                                                                                                                                         
          - /sixer/Pictures:/mnt/Pictures                                                                                                                                                                                                                                                                            
        cpu_count: 8                                                                                                                                                                                                                                                                                                 
        mem_limit: 16G                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                                     
        networks:                                                                                                                                                                                                                                                                                                    
             - multimedia                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                     
networks:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    multimedia:                                                                                                                                                                                                                                                                                                      
        external: true                                                                                                                                                                                                                                                                                               
        name: multimedia
```
